# Generated by Django 3.0.3 on 2020-02-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('props', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Difficult')], max_length=100)),
            ],
        ),
    ]
