# Generated by Django 3.0.3 on 2020-02-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('partner_name', models.CharField(max_length=100)),
                ('code', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='questions',
            name='type',
            field=models.CharField(choices=[('1', 'Easy'), ('2', 'Medium'), ('3', 'Difficult')], max_length=100),
        ),
    ]
